#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: product-api
  namespace: istio-system
spec:
  commonName: #@ data.values.ingress_hostname
  dnsNames:
  - #@ data.values.ingress_hostname
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: product-api-tls