#@ load("@ytt:data", "data")

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-api-virtual-service
  namespace: product-api
spec:
  hosts:
    - #@ data.values.ingress_hostname
  gateways:
    - app-gateway.istio-system.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: product-api
        port:
          number: 8080