#@ load("@ytt:data", "data")

apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: product-api
  namespace: images
spec:
  tag: #@ data.values.harbor_domain + "/library/product-api"
  serviceAccount: tbs-service-account
  builder:
    name: base
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/techgnosis/product-api.git
      revision: demo

