#@ load("@ytt:data", "data")
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: concourse
  namespace: concourse
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: #@ data.values.concourse_hostname
    http:
      paths:
      - backend:
          serviceName: concourse-web
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - #@ data.values.concourse_hostname
    secretName: concourse-web-tls