#@ load("@ytt:data", "data")

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: concourse-virtual-service
  namespace: concourse
spec:
  hosts:
    - #@ data.values.concourse_hostname
  gateways:
    - concourse-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: concourse-web
        port:
          number: 8080