apiVersion: v1
kind: Secret
metadata:
  name: settings-xml
  namespace: images
type: Opaque
stringData:
  settings.xml: |
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">

    <mirrors>
      <mirror>
        <id>nexus</id>
        <name>nexus</name>
        <url>https://nexus.whatever</url>
        <mirrorOf>*</mirrorOf>
      </mirror>
    </mirrors>

    <servers>
      <server>
        <id>nexus</id>
        <username>my_login</username>
        <password>my_password</password>
      </server>
    </servers>

    </settings>