#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: harbor-notary
  namespace: harbor
spec:
  commonName: #@ "notary." + data.values.primary_domain
  dnsNames:
  - #@ "notary." + data.values.primary_domain
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: harbor-notary