apiVersion: v1
kind: Namespace
metadata:
  name: postgres-dbs
---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: testdb
  namespace: postgres-dbs
spec:
  memory: "800Mi"
  cpu: "0.5"
  storageClassName: vsan
  serviceType: ClusterIP
  storageSize: 300M
  pgConfig:
    dbname: testdb
    username: testdb