resources:
- name: concourse-helper
  type: docker-image
  source:
    repository: ((harbordomain))/library/concourse-helper
    tag: 1
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))
- name: tanzu-gitops
  type: git
  source:
    uri: https://github.com/techgnosis/tanzu-gitops.git
    branch: master
    paths:
      - "concourse/tasks/**"

jobs:
- name: Sync Helm charts to Harbor
  public: true
  serial: true
  plan:
  - get: concourse-helper
  - get: tanzu-gitops
  - task: sync TAC to Harbor
    image: concourse-helper
    file: tanzu-gitops/concourse/tasks/charts-syncer/charts-syncer.yml

