apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: wavefront
data:
  telegraf.conf: |
    [[inputs.vsphere]]
      vcenters = [ "https://vcsa.lab.home/sdk" ]
      username = "administrator@vsphere.local"
      password = "yDZZn&zHf3fTiXhHNeo"
      insecure_skip_verify = true

    [[inputs.mysql]]
      servers = ["petclinic:petclinic@tcp(mysql.spring-petclinic.svc.cluster.local:3306)/?tls=false"]

    [[inputs.mongodb]]
      servers = [
        "mongodb://carts-db.sock-shop.svc.cluster.local:27017",
        "mongodb://orders-db.sock-shop.svc.cluster.local:27017",
        "mongodb://user-db.sock-shop.svc.cluster.local:27017"
      ]


    [[outputs.wavefront]]
      host = "wavefront-proxy.wavefront.svc.cluster.local"
      port = 2878
      metric_separator = "."
      source_override = ["hostname", "agent_host", "node_host"]
      convert_paths = true
 