#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: minio
  namespace: minio
spec:
  commonName: #@ "minio." + data.values.apps_domain
  dnsNames:
  - #@ "minio." + data.values.apps_domain
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: minio-tls