#@ load("@ytt:data", "data")
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio
  namespace: minio
spec:
  rules:
  - host: #@ "minio." + data.values.apps_domain
    http:
      paths:
      - backend:
          serviceName: minio
          servicePort: 9000
        path: /
  tls:
  - hosts:
    - #@ "minio." + data.values.apps_domain
    secretName: minio-tls